---
description: Turn on lights in Garage based on motion
alias: motion_in_garage
id: '8599383727852'
mode: single
trigger:
    platform: state
    entity_id: group.garage_sensors
    to: 'on'
action:
  # - service: notify.mobile_app_shanes_iphone
  #   data:
  #       message: Motion in the scullery 🤖
  - service: light.turn_on
    data: 
        entity_id: light.garage_lights
  - delay: 00:05:00
  - service: light.turn_off
    data:
      entity_id: light.garage_lights
  # - service: notify.mobile_app_shanes_iphone
  #   data:
  #       message: Lights off in scullery
    