---
description: Send notification when scenes are reloaded
alias: system_scene_reloaded_notification
id: c8dffcdc-6d66-4bcf-b823-19a0bc2b1a97
mode: single
trigger:
  platform: event
  event_type: scene_reloaded
action:
  - service: notify.mobile_app_shanes_iphone
    data:
      message: Home Assistant reloaded all scenes 🌈
